services:
  - type: web
    name: artconnect
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: |
      php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://artconnect.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromService: mysql-db
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: artconnect
      - key: DB_USERNAME
        value: artuser
      - key: DB_PASSWORD
        generateValue: true

databases:
  - name: mysql-db
    plan: free
    ipAllowList: [] # allows connections only from your Render service
    databaseName: artconnect
    user: artuser
